name: flashcard-app

services:
  vite-app:
    build: .
    container_name: flashcard-frontend-app  # Make this more unique
    restart: unless-stopped
    ports:
      - "8093:80"
    volumes:
      - ./dist:/usr/share/nginx/2025-flashcard-api-front
